### ISSUE TITLE
Tracking Plans vs Authentication vs Scripts

### ISSUE THREAD

**Issue by TWiStErRob** [rudderlabs/rudder-typer#111]
## Description

Here's an example `ruddertyper.yml`. It pulls data from 2 workspaces and puts them in different folders. Notice how the scripts section is general to all trackingPlans. This makes it impossible to pull data from 2 workspaces, because the PATs are associated to different workspaces. These 2 workspaces could even be in different organisations. Similarly the `after:` script is specific to each tracking plan, yet they have to be bundled together.

```yml
scripts:
  token: echo $RUDDERTYPER_TOKEN
  email: echo $RUDDERTYPER_EMAIL
  # Repackage code (template has hardcoded Java package names)
  after: |
    sed -i '' -e 's/com.rudderstack.ruddertyper.generated/com.example.rudderstack.events.generic/g' src/main/kotlin/com/example/rudderstack/events/generic/*.java
    sed -i '' -e 's/com.rudderstack.ruddertyper.generated/com.example.rudderstack.events.special/g' src/main/kotlin/com/example/rudderstack/events/special/*.java

client:
  sdk: analytics-android
  language: java

trackingPlans:
  - id: tp_2foobar
    version: 123
    workspaceSlug: 2fluxbar
    path: src/main/java/com/example/rudderstack/events/generic
    APIVersion: v2

  - id: tp_2foobaz
    version: 321
    workspaceSlug: 2quxmux
    path: src/main/java/com/example/rudderstack/events/special
    APIVersion: v2
```

I think an improvement on the model would be to allow defining scripts inside each tracking plan:

```yml
client:
  sdk: analytics-android
  language: java

trackingPlans:
  - id: tp_2foobar
    version: 123
    workspaceSlug: 2fluxbar
    path: src/main/java/com/example/rudderstack/events/generic
    APIVersion: v2
    scripts:
      token: echo $RUDDERTYPER_GENERIC_TOKEN
      email: echo $RUDDERTYPER_GENERIC_EMAIL
      after: sed -i '' -e 's/com.rudderstack.ruddertyper.generated/com.example.rudderstack.events.generic/g' src/main/kotlin/com/example/rudderstack/events/generic/*.java

  - id: tp_2foobaz
    version: 321
    workspaceSlug: 2quxmux
    path: src/main/java/com/example/rudderstack/events/special
    APIVersion: v2
    scripts:
      token: echo $RUDDERTYPER_SPECIAL_TOKEN
      email: echo $RUDDERTYPER_SPECIAL_EMAIL
      after: sed -i '' -e 's/com.rudderstack.ruddertyper.generated/com.example.rudderstack.events.special/g' src/main/kotlin/com/example/rudderstack/events/special/*.java
```

A similar thing might be said about `client:` too.

Granted this can be all worked around by creating many `ruddertyper.yml` files, one for each, but then it kind of defeats the purpose of having an array of `trackingPlans`.
